### ISSUE TITLE
Enhancement:  Allow user attributes accept xpath

### ISSUE THREAD

**Issue by sueb226** [CGCookie/wp-cassify#5]
Could the User Attributes field be expanded to accept Xpath?
For example: to select the text of the only one element of a  subset

`<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
<cas:authenticationSuccess>
    <cas:user>******</cas:user>
    <cas:attributes>
        <cas:eduPersonPrincipalName>******</cas:eduPersonPrincipalName>
        <cas:sn>Prefered Surname</cas:sn>
        <cas:sn>Legal Surname</cas:sn>
        <cas:mail>username@email.com</cas:mail>
        <cas:displayName>Prefered Given Name Prefered Surname</cas:displayName>
        <cas:givenName>Prefered Given Name</cas:givenName>
        <cas:givenName>Legal Given Name</cas:givenName>
        </cas:attributes>
</cas:authenticationSuccess>
</cas:serviceResponse>
`

**Comment by carter2422** [comment]
@sueb226 this repository is no longer maintained. You're welcome to fork the repo and make any changes you'd like, though!
